import { DayPlan } from './types';

export const WEEKLY_PLAN: DayPlan[] = [
  {
    day: 1,
    title: "Понедельник",
    theme: "Знакомство (Hello & Introductions)",
    grammarFocus: "Глагол 'to be' (am/is/are)",
    isLocked: false,
    isCompleted: false,
    lesson: 1,
  },
  {
    day: 2,
    title: "Вторник",
    theme: "Моя семья (My Family)",
    grammarFocus: "Притяжательные местоимения (my, your)",
    isLocked: false,
    isCompleted: false,
    lesson: 2,
  },
  {
    day: 3,
    title: "Среда",
    theme: "Распорядок дня (Daily Routine)",
    grammarFocus: "Present Simple (I do / He does)",
    isLocked: false,
    isCompleted: false,
    lesson: 3,
  },
  {
    day: 4,
    title: "Четверг",
    theme: "В кафе (At the Cafe)",
    grammarFocus: "A / An / Some / Any",
    isLocked: true,
    isCompleted: false,
    lesson: 4,
  },
  {
    day: 5,
    title: "Пятница",
    theme: "Хобби (Free Time & Hobbies)",
    grammarFocus: "Can / Can't (Способности)",
    isLocked: true,
    isCompleted: false,
    lesson: 5,
  },
  {
    day: 6,
    title: "Суббота",
    theme: "Мой дом (My Apartment)",
    grammarFocus: "Оборот There is / There are",
    isLocked: true,
    isCompleted: false,
    lesson: 6,
  },
  {
    day: 7,
    title: "Воскресенье",
    theme: "Прошлые выходные (Last Weekend)",
    grammarFocus: "Past Simple (Was/Were)",
    isLocked: true,
    isCompleted: false,
    lesson: 7,
  },
];