platform :ios, '15.0'
use_frameworks!

require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

install! 'cocoapods', :deterministic_uuids => false

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
end

target 'App' do
  capacitor_pods
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
